controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

    tool_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - jointPWM
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

